# Generated by Django 6.0.4 on 2026-04-29 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('product_count', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('stock_store', models.PositiveIntegerField(default=0)),
                ('stock_warehouse', models.PositiveIntegerField(default=0)),
                ('is_best_price', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
