# Generated by Django 6.0.4 on 2026-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Адрес доставки'),
        ),
    ]
