# Generated by Django 6.0.4 on 2026-05-01 12:46

import django.db.models.deletion
from django.db import migrations, models


def migrate_product_specs_json_forward(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    CategorySpecAttribute = apps.get_model("shop", "CategorySpecAttribute")
    ProductSpecValue = apps.get_model("shop", "ProductSpecValue")
    for product in Product.objects.all():
        specs = product.specs or {}
        if not specs:
            continue
        if ProductSpecValue.objects.filter(product_id=product.pk).exists():
            continue
        for idx, (name, val) in enumerate(specs.items()):
            attr, _ = CategorySpecAttribute.objects.get_or_create(
                category_id=product.category_id,
                name=name,
                defaults={"sort_order": idx},
            )
            ProductSpecValue.objects.update_or_create(
                product_id=product.pk,
                attribute_id=attr.pk,
                defaults={"value": str(val)},
            )
        Product.objects.filter(pk=product.pk).update(specs={})


def migrate_product_specs_json_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_russian_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text='Не используйте для новых данных — задайте характеристики категории и значения у товара.', verbose_name='Характеристики (JSON, устар.)'),
        ),
        migrations.CreateModel(
            name='CategorySpecAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_attributes', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Характеристика категории',
                'verbose_name_plural': 'Характеристики категории',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=512, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='shop.categoryspecattribute', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
            },
        ),
        migrations.AddConstraint(
            model_name='categoryspecattribute',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_category_spec_attribute_name'),
        ),
        migrations.AddConstraint(
            model_name='productspecvalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute'), name='uniq_product_spec_value_attribute'),
        ),
        migrations.RunPython(migrate_product_specs_json_forward, migrate_product_specs_json_backward),
    ]
