# Generated by Django 6.0.4 on 2026-05-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_product_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Мета-описание для поиска (рекомендуется до ~320 символов).', max_length=320, verbose_name='SEO — description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы в браузере и для поисковиков. Пусто — используется название категории.', max_length=255, verbose_name='SEO — title'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Мета description для поиска (рекомендуется до ~320 символов).', max_length=320, verbose_name='SEO — description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок вкладки и для поисковиков. Пусто — используется название товара.', max_length=255, verbose_name='SEO — title'),
        ),
    ]
