# Generated by Django 6.0.4 on 2026-05-01 13:03

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_category_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Каталог на сервере: products/<slug категории>/файл. Если файл загружен, он имеет приоритет над URL.', null=True, upload_to=shop.models.product_image_upload_to, verbose_name='Изображение (загрузка)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Внешняя ссылка. Обязательно, если файл не загружен.', verbose_name='URL изображения'),
        ),
    ]
