# Generated by Django 6.0.4 on 2026-05-01 15:49

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_gallery_images_limit10'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Если файл загружен, он имеет приоритет над URL.', null=True, upload_to=shop.models.category_image_upload_to, verbose_name='Изображение (загрузка)'),
        ),
    ]
