# Generated by Django 6.0.4 on 2026-05-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_seed_content_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='Изображение для карточки в списке (рекомендуется 800×450).', max_length=500, verbose_name='URL обложки'),
        ),
        migrations.AddField(
            model_name='article',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='news',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, help_text='Изображение для карточки в списке (рекомендуется 800×450).', max_length=500, verbose_name='URL обложки'),
        ),
        migrations.AddField(
            model_name='news',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_url',
            field=models.URLField(blank=True, help_text='Изображение для карточки в списке (рекомендуется 800×450).', max_length=500, verbose_name='URL обложки'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
