# Generated by Django 6.0.4 on 2026-05-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_content_page_visuals_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='yandex_feed_enabled',
            field=models.BooleanField(default=True, help_text='Товары категории по умолчанию попадают в YML-фид (/feeds/yandex.xml), если у товара не задано иное.', verbose_name='В фиде Яндекс Маркета'),
        ),
        migrations.AddField(
            model_name='categoryspecattribute',
            name='yandex_feed_include',
            field=models.BooleanField(default=True, help_text='По умолчанию выгружать эту характеристику в YML-фид для всех товаров категории.', verbose_name='В фиде Яндекс Маркета'),
        ),
        migrations.AddField(
            model_name='categoryspecattribute',
            name='yandex_feed_param_role',
            field=models.CharField(choices=[('param', 'Параметр (<param>)'), ('vendor', 'Производитель (<vendor>)'), ('barcode', 'Штрихкод (<barcode>)')], default='param', help_text='Как передать значение в YML: обычный param, vendor или barcode.', max_length=16, verbose_name='Роль в фиде'),
        ),
        migrations.AddField(
            model_name='product',
            name='yandex_feed_include_description',
            field=models.BooleanField(default=True, help_text='Выгружать поле description в YML-фид.', verbose_name='Описание в фиде'),
        ),
        migrations.AddField(
            model_name='product',
            name='yandex_feed_mode',
            field=models.CharField(choices=[('inherit', 'Как в категории'), ('include', 'Включить в фид'), ('exclude', 'Исключить из фида')], default='inherit', help_text='«Как в категории» — по галочке категории. Можно принудительно включить или исключить товар.', max_length=16, verbose_name='Фид Яндекс Маркета'),
        ),
        migrations.AddField(
            model_name='productspecvalue',
            name='yandex_feed_include',
            field=models.BooleanField(blank=True, default=None, help_text='Пусто — как у характеристики категории. Да/нет — переопределение для этого товара.', null=True, verbose_name='В фиде Яндекс Маркета'),
        ),
    ]
