# Generated by Django 6.0.5 on 2026-05-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_top_menu_link_content_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topmenulink',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Страница верхнего меню', 'verbose_name_plural': 'Верхнее меню'},
        ),
    ]
